// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Db.DAL.Models;

public partial class invoice
{
    [StringLength(50)]
    public string applicant { get; set; }

    [StringLength(50)]
    public string approve_by { get; set; }

    [StringLength(50)]
    public string division { get; set; }

    [StringLength(50)]
    public string department { get; set; }

    public DateOnly? date { get; set; }

    [StringLength(50)]
    public string bill_type { get; set; }

    [StringLength(10)]
    public string pd_type { get; set; }

    [StringLength(50)]
    public string vendor { get; set; }

    [StringLength(10)]
    public string total_base_amount { get; set; }

    [Key]
    public int id { get; set; }
}