// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Db.DAL.Models;

public partial class Jifas_MagangContext : DbContext
{
    public Jifas_MagangContext()
    {
    }

    public Jifas_MagangContext(DbContextOptions<Jifas_MagangContext> options)
        : base(options)
    {
    }

    public virtual DbSet<invoice> invoice { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=10.0.8.51;Initial Catalog=Jifas_Magang;Persist Security Info=True;User ID=magang.it10;Password=magangit10;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<invoice>(entity =>
        {
            entity.Property(e => e.pd_type).IsFixedLength();
            entity.Property(e => e.total_base_amount).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}